### ISSUE TITLE
Can not open recording device

### ISSUE THREAD

**Issue by aardrasystems** [Omegaframe/alsa.net#4]
Hi 

I am getting the following error.

I am using this library in .net C# project on a RaspberryPi. The aim is to capture audio. from a USB mic. 

How can I specify the USB mic or get a list of device to connect with?

```
An unhandled exception of type 'Alsa.Net.Internal.AlsaDeviceException' occurred in Alsa.Net.dll: 'Alsa Error: Can not open recording device. Error -2. No such file or directory.'
   at Alsa.Net.Internal.UnixSoundDevice.ThrowErrorMessage(Int32 errorNum, String message)
   at Alsa.Net.Internal.UnixSoundDevice.OpenRecordingPcm()
   at Alsa.Net.Internal.UnixSoundDevice.Record(Stream saveStream, CancellationToken token)
   at Alsa.Net.Internal.UnixSoundDevice.Record(UInt32 second, Stream saveStream)
   at Alsa.Net.Internal.UnixSoundDevice.Record(UInt32 second, String savePath)
   at Program.Main(String[] args) in /home/dotnet.core.iot.csharp/Program.cs:line 12
```

**Comment by aardrasystems** [comment]
This is the output I get, how do i set the USB mic to record

```
djosh@raspberrypi:~ $ arecord -L
null
    Discard all samples (playback) or generate zero samples (capture)
default
    Default Audio Device
sysdefault
    Default Audio Device
hw:CARD=Microphone,DEV=0
    USB Microphone, USB Audio
    Direct hardware device without any conversions
plughw:CARD=Microphone,DEV=0
    USB Microphone, USB Audio
    Hardware device with all software conversions
default:CARD=Microphone
    USB Microphone, USB Audio
    Default Audio Device
sysdefault:CARD=Microphone
    USB Microphone, USB Audio
    Default Audio Device
front:CARD=Microphone,DEV=0
    USB Microphone, USB Audio
    Front output / input
dsnoop:CARD=Microphone,DEV=0
    USB Microphone, USB Audio
    Direct sample snooping device
```
